name: Deploy to Cloud Run Jobs

on:
  push:
    branches: [ main ] # Only main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Google Cloud Authorization
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run Jobs
        run: |
          gcloud run jobs deploy aviation-etl-job \
            --image europe-west4-docker.pkg.dev/aviation-data-project/cloud-run-source-deploy/aviation-etl-job \
            --region europe-west4 \
            --set-env-vars AVIATION_API_KEY=${{ secrets.AVIATION_API_KEY }},GCP_PROJECT_ID=aviation-data-project